export const queriesDeepExamples = {
    title: 'REST queries, filters, meta counts, and deep relation fetches',
    useWhen: 'Use when fetching records, filtering by relations, loading nested relation data in the same request, or counting efficiently.',
    examples: [
      {
        name: 'Minimal MCP query then explicit detail query',
        code: `query_table({
  tableName: "enfyra_user",
  fields: ["id", "email"],
  filter: { email: { _contains: "@example.com" } },
  limit: 10
})`,
        notes: [
          'Always pass fields when you need more than ids; query_table without fields intentionally returns only the primary key.',
          'Use inspect_table first when you do not know valid column names or relation propertyName values.',
          'Use count_records when only the count is needed.',
          'When the user asks for all matching rows, pass all: true instead of choosing an arbitrary page size such as 30 or 50.',
        ],
      },
      {
        name: 'List current user conversations through RLS',
        code: `query_table({
  tableName: "chat_conversation",
  fields: ["id", "kind", "title", "lastMessage.id", "lastMessage.text", "lastMessage.createdAt"],
  all: true
})`,
        notes: [
          'Use a conversation read pre-hook/RLS boundary so the route only returns conversations visible to @USER.',
          'lastMessage is a relation to chat_message; do not duplicate preview fields on chat_conversation.',
          'all: true tells MCP to send REST limit=0 and load all matching conversation rows.',
          'This is a small bounded user inbox example. For larger inventories, prefer pagination even when RLS scopes the records.',
          'Do not fetch messages for every conversation on initial list load; load messages after selecting a conversation.',
        ],
      },
      {
        name: 'Fetch one record by id',
        code: `find_one_record({
  tableName: "post",
  id: "123",
  fields: ["id", "title", "createdAt"]
})

// REST equivalent after inspecting metadata primary key:
GET /enfyra/post?filter={"<primaryKeyFromMetadata>":{"_eq":123}}&limit=1`,
        notes: [
          'There is no dynamic GET /<table>/<id> route.',
          'Prefer MCP find_one_record because it resolves the primary key from live metadata.',
          'If writing raw REST, inspect metadata first and use the real primary key field; do not assume id on every backend.',
        ],
      },
      {
        name: 'Count without loading all rows',
        code: `query_table({
  tableName: "chat_message_read",
  fields: ["id"],
  limit: 1,
  meta: "filterCount",
  filter: {
    member: { id: { _eq: "<currentUserId>" } },
    isRead: { _eq: false }
  }
})`,
        notes: [
          'Use meta=totalCount with no filter and meta=filterCount with a filter.',
          'MCP count_records wraps this pattern for simple counts.',
          'Do not fetch all rows only to count them.',
        ],
      },
      {
        name: 'Relation fields without deep',
        code: `query_table({
  tableName: "order",
  fields: [
    "id",
    "total",
    "customer.id",
    "customer.email",
    "customer.displayName"
  ],
  limit: 20
})`,
        notes: [
          'Use fields with dotted relation paths when you only need scalar fields from related records.',
          'This is enough for simple many-to-one or one-to-one relation display such as owner.email, customer.name, or lastMessage.text.',
          'Treat order/customer as placeholders; the transferable idea is "show parent rows with a few scalar relation fields".',
          'Do not add deep when fields alone can express the relation data you need.',
        ],
      },
      {
        name: 'Exclude large generated fields',
        code: `query_table({
  tableName: "enfyra_route_handler",
  fields: ["-compiledCode"],
  limit: 20
})

query_table({
  tableName: "post",
  fields: ["id", "-author.avatar"],
  deep: {
    comments: {
      fields: "-compiledCode,-author.avatar",
      limit: 10,
      deep: {
        author: { fields: "-avatar" }
      }
    }
  }
})`,
        notes: [
          'Use fields=-compiledCode when reading script-backed records; sourceCode is the editable contract and compiledCode is generated by the server.',
          'Any -field token switches that fields scope to exclude mode, so fields=id,-compiledCode returns all readable fields except compiledCode.',
          'Dotted exclusions and deep relation fields use the same exclude-mode rule.',
          'Excluded fields and relations must exist in metadata; typos should fail instead of silently returning large or sensitive fields.',
        ],
      },
      {
        name: 'Deep relation query options',
        code: `query_table({
  tableName: "order",
  fields: ["id", "total"],
  deep: {
    items: {
      fields: "id,quantity,product",
      sort: "-createdAt",
      limit: 20,
      deep: {
        product: { fields: "id,name,price" }
      }
    }
  }
})`,
        notes: [
          'Use deep when relation loading needs query options such as filter, sort, limit, page, or nested deep.',
          'Deep is mainly useful for controlled child collections or nested relation fetches, not for basic related-field display.',
          'Do not use deep just to filter by a relation id; use a normal relation filter instead.',
          'Do not use deep for counts; use count_records or meta=filterCount/totalCount.',
          'Do not deep-load large child collections without an explicit limit/page. For heavy screens, fetch the parent list first, then load the selected child collection separately with pagination.',
          'Use query_table deep for normal MCP reads; use test_rest_endpoint only when you need a custom raw URL or route behavior test.',
          'deep keys must be relation property names.',
          'Allowed deep options are fields, filter, sort, limit, page, and deep.',
          'Use fields, never _fields, inside deep relation options.',
          'Do not invent deep keys like members unless members is a relation on that table.',
        ],
      },
      {
        name: 'Sort parent rows by child relation aggregates',
        code: `query_table({
  tableName: "cloud_support_tickets",
  fields: [
    "id",
    "subject",
    "status",
    "project.id",
    "project.name"
  ],
  sort: "-_max(messages.createdAt),-createdAt",
  limit: 25,
  deep: JSON.stringify({
    messages: {
      fields: "id,authorKind,body,createdAt",
      sort: "-createdAt",
      limit: 3
    }
  })
})

// Other parent aggregate sorts:
// sort=-_count(messages)
// sort=_min(messages.createdAt)`,
        notes: [
          'Use _max(relation.field) for latest-child ordering, _min(relation.field) for earliest-child ordering, and _count(relation) for child-count ordering.',
          'Aggregate sort helpers only work on direct one-to-many or many-to-many list relations.',
          'Support tickets and messages are illustrative. Apply this when a parent list must be ordered by child recency or child volume.',
          'The aggregate field must be a real published, non-encrypted scalar field on the related table for user-facing APIs.',
          'Do not use _max, _min, or _count on private relations or unpublished fields unless the endpoint intentionally exposes that fact.',
          'Do not use raw sort=-messages.createdAt for parent ordering; it is ambiguous and rejected.',
          'deep.messages.sort only orders the loaded message rows inside each ticket, so keep parent sort and child pagination as separate concerns.',
        ],
      },
      {
        name: 'Encrypted fields are not lookup fields',
        code: `// Bad: api_token is isEncrypted=true, so filter/sort cannot use it.
GET /enfyra/integrations?filter={"api_token":{"_eq":"plaintext-token"}}

// Good: store a separate non-secret lookup hash if lookup is needed.
create_columns({
  globalRulesAckKey: "<globalRulesAckKey from get_enfyra_required_knowledge>",
  items: [
    {
      tableId: "<integrations_table_id>",
      name: "api_token_lookup_sha256",
      type: "varchar",
      isNullable: false,
      isPublished: false
    }
  ]
})

// In the create/update handler or pre-hook, hash plaintext before it is encrypted.
if (@BODY.api_token) {
  @BODY.api_token_lookup_sha256 = await @HELPERS.$crypto.sha256(@BODY.api_token)
}

// Lookup by the hash, never by the encrypted field.
const lookup = await @HELPERS.$crypto.sha256(@BODY.api_token)
const found = await #integrations.find({
  filter: { api_token_lookup_sha256: { _eq: lookup } },
  limit: 1
})`,
        notes: [
          'isEncrypted values are encrypted at rest and decrypted after select.',
          'Do not filter, sort, or deep-filter by encrypted fields.',
          'Use a separate deterministic non-secret hash/lookup column when the product needs secret-derived lookup.',
          'Do not ask clients to submit enc:v1: ciphertext.',
        ],
      },
    ],
  };
