export const graphqlExamples = {
    title: 'GraphQL table exposure, queries, mutations, and verification',
    useWhen: 'Use when enabling generated GraphQL for a table or executing a GraphQL operation through Enfyra.',
    examples: [
      {
        name: 'Enable a table and verify its generated query',
        code: `inspect_table({ tableName: "project" })

set_table_graphql({
  tableName: "project",
  isEnabled: true,
  globalRulesAckKey: "<globalRulesAckKey from get_enfyra_required_knowledge>"
})

test_graphql({
  operationName: "VerifyProjects",
  query: \`query VerifyProjects {
    project(limit: 1) {
      data { id name }
      meta { totalCount }
    }
  }\`
})`,
        notes: [
          'GraphQL root query names match enabled Enfyra table names and return data plus meta.',
          'Only select fields confirmed by inspect_table or the live GraphQL schema; unpublished fields are not generated.',
          'GraphQL table operations require Bearer authentication even when the REST route has publicMethods.',
          'enfyra_graphql stores exposure metadata. Resolvers are generated by Enfyra and do not have editable sourceCode.',
        ],
      },
      {
        name: 'Execute a generated GraphQL mutation with variables',
        code: `test_graphql({
  operationName: "CreateTodo",
  query: \`mutation CreateTodo($input: todoInput!) {
    create_todo(input: $input) {
      id
      title
      status
    }
  }\`,
  variables: {
    input: {
      title: "Review GraphQL contract",
      status: "open"
    }
  }
})`,
        notes: [
          'Generated mutation names are create_<table>, update_<table>, and delete_<table>.',
          'Inspect the live schema before choosing input fields because required fields and scalar types come from current table metadata.',
          'test_graphql returns GraphQL errors as structured data; do not treat HTTP 200 alone as success.',
        ],
      },
    ],
  };
