import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, realpath, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { ListRootsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { installToolsetFilter } from '../dist/lib/toolset-filter.js';
import { installToolAnnotations } from '../dist/lib/tool-contracts.js';
import { registerToolCatalogTools } from '../dist/lib/tool-catalog.js';
import { registerWorkspaceTools } from '../dist/lib/workspace-tools.js';
import { installToolOutputContracts } from '../dist/lib/tool-output-contracts.js';
import { installColumnarToolFormatter, jsonContent } from '../dist/lib/response-format.js';
import { writeSourceArtifact, readSourceArtifactResource } from '../dist/lib/source-artifacts.js';
import { resetMcpSafetySession } from '../dist/lib/session-safety.js';

test('SDK workspace uses client roots, ignores source and routes artifacts to project tmp through one tool', async (t) => {
  const root = await realpath(await mkdtemp(join(tmpdir(), 'enfyra-sdk-workspace-')));
  execFileSync('git', ['init', '-q', root]);
  const server = new McpServer({ name: 'workspace-sdk', version: '1.0.0' });
  installToolOutputContracts(server);
  installColumnarToolFormatter(server);
  const state = installToolsetFilter(server, 'guided');
  installToolAnnotations(server);
  server.tool('get_enfyra_api_context', '', {}, async () => jsonContent({ targetInstance: { apiBase: 'https://workspace.example/api', source: 'fixture' }, enfyraApiUrl: 'https://workspace.example/api', graphqlHttpUrl: 'https://workspace.example/api/graphql', graphqlSchemaUrl: 'https://workspace.example/api/graphql-schema', auth: {} }));
  server.tool('inspect_table', '', {}, async () => jsonContent({ source: writeSourceArtifact({ tableName: 'fixture', id: 1, fieldName: 'sourceCode', source: 'return 1;' }) }));
  const workspace = registerWorkspaceTools(server, state, 'https://workspace.example/api');
  registerToolCatalogTools(server, state, { sourceDirectory: workspace.artifactDirectory });
  const client = new Client({ name: 'workspace-sdk-client', version: '1.0.0' }, { capabilities: { roots: {} } });
  client.setRequestHandler(ListRootsRequestSchema, async () => ({ roots: [{ uri: pathToFileURL(root).href }] }));
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);
  await client.connect(clientTransport);
  t.after(async () => { await client.close(); await server.close(); resetMcpSafetySession(); await rm(root, { recursive: true, force: true }); });
  const call = (name, args = {}) => client.callTool({ name: 'enfyra', arguments: { action: 'execute', name, arguments: args } });
  assert.equal((await call('inspect_table')).isError, true);
  assert.equal((await call('prepare_enfyra_workspace', { artifacts: [] })).isError, true);
  await call('get_enfyra_api_context');
  const prepared = await call('prepare_enfyra_workspace', { artifacts: [] });
  assert.notEqual(prepared.isError, true, JSON.stringify(prepared));
  assert.equal(prepared.structuredContent.result.projectRoot, root);
  const inspected = await call('inspect_table');
  const source = inspected.structuredContent.result.source;
  assert.ok(source.tmpFile.startsWith(join(root, '.tmp', 'enfyra')));
  assert.equal(await readFile(source.tmpFile, 'utf8'), 'return 1;');
  assert.equal(readSourceArtifactResource(source.resourceUri).text, 'return 1;');
  execFileSync('git', ['-C', root, 'check-ignore', '-q', source.tmpFile]);
  assert.deepEqual((await client.listTools()).tools.map(({ name }) => name), ['enfyra']);
});
